version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule: { interval: "weekly" }
    ignore:
      - dependency-name: "phpstan/phpstan"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly" }
    ignore:
      - dependency-name: "actions/checkout"
        update-types: ["version-update:semver-major"]
