name: Publish API Docs (ReDoc)

on:
  push:
    branches: [ main ]
    paths:
      - 'openapi.yaml'
      - '.github/workflows/api-docs.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build ReDoc (static HTML)
        run: |
          npm i -g @redocly/cli
          redocly build-docs openapi.yaml -o site/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
