name: Publish API Docs (ReDoc)

on:
  push:
    branches: [ main ]
    paths:
      - 'openapi.yaml'
      - '.github/workflows/api-docs.yml'

# Add permissions for GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build ReDoc Documentation
        run: |
          npm i -g @redocly/cli
          mkdir -p site
          redocly build-docs openapi.yaml -o site/index.html
          
          # Create a simple landing page
          cat > site/README.md << 'EOF'
          # API Documentation
          
          ## Interactive API Documentation
          
          View the interactive API documentation: [API Docs](./index.html)
          
          ## OpenAPI Specification
          
          Download the OpenAPI specification: [openapi.yaml](../openapi.yaml)
          
          ## Quick Start
          
          ```bash
          # Health check
          curl https://api.your-domain.com/api/health
          
          # Get products
          curl https://api.your-domain.com/api/products
          ```
          EOF
          
          # Copy OpenAPI spec for direct access
          cp openapi.yaml site/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
