name: CI (PHP)
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
      - run: composer install --no-interaction --prefer-dist
      - run: vendor/bin/phpunit
      - run: vendor/bin/phpstan analyse app --level=max
      - run: vendor/bin/phpcs --standard=PSR12 app
